<?php

namespace App\Services\Payments\Doku;

use App\Contracts\Payments\PaymentGateway;
use App\Models\BillingInvoice;
use App\Models\DokuVaChannel;
use App\Models\Member;
use Illuminate\Support\Str;

class DokuPaymentGateway implements PaymentGateway
{
    public function __construct(private readonly DokuClient $client) {}

    public function createPaymentAttempt(BillingInvoice $invoice, string $method): array
    {
        return match ($method) {
            'va' => $this->createInvoiceVa($invoice),
            'qris' => $this->createQris($invoice),
            default => throw new DokuException('Metode pembayaran DOKU tidak didukung: ' . $method),
        };
    }

    public function createReusableVirtualAccount(Member $member, string $bank = ''): array
    {
        $code = strtoupper(trim($bank));
        $channel = $code !== ''
            ? DokuVaChannel::forDoku()->enabled()->where('code', $code)->first()
            : DokuVaChannel::defaultDoku();

        if (! $channel) {
            throw new DokuException('Channel Virtual Account DOKU tidak ditemukan atau tidak aktif.');
        }

        $isDgpc = filled($channel->merchant_bin);
        $partnerServiceId = $isDgpc
            ? $this->normalizePartnerServiceId((string) $channel->merchant_bin)
            : $this->normalizePartnerServiceId((string) ($channel->partner_service_id ?: config('doku.va_partner_service_id')));

        if (trim($partnerServiceId) === '') {
            throw new DokuException('Kode merchant DOKU untuk ' . $channel->name . ' belum dikonfigurasi.');
        }

        $trxId = 'MEM-' . $member->id . '-' . Str::lower(Str::random(10));
        $payload = [
            'partnerServiceId' => $partnerServiceId,
            'virtualAccountName' => Str::limit($member->username, 255, ''),
            'trxId' => $trxId,
            'totalAmount' => [
                'value' => number_format((int) $member->price_snapshot, 2, '.', ''),
                'currency' => 'IDR',
            ],
            'additionalInfo' => [
                'channel' => $channel->channel,
                'virtualAccountConfig' => [
                    'reusableStatus' => true,
                ],
            ],
            'virtualAccountTrxType' => 'C',
        ];

        if ($isDgpc) {
            // DGPC uses the merchant BIN as partnerServiceId. The DOKU channel
            // configuration requires a stable 20-digit customer number; the VA
            // number itself is generated by DOKU and returned in the response.
            $payload['customerNo'] = $this->customerNumber($member->id, $this->normalizeCustomerPrefix($channel->customer_prefix));
        } else {
            $customerPrefix = $this->normalizeCustomerPrefix($channel->customer_prefix);
            $customerNo = $this->customerNumber($member->id, $customerPrefix);
            $payload['customerNo'] = $customerNo;
            $payload['virtualAccountNo'] = $this->buildVirtualAccountNumber($partnerServiceId, $customerNo);
        }

        $response = $this->client->postSnap(
            '/virtual-accounts/bi-snap-va/v1.1/transfer-va/create-va',
            $payload,
            config('doku.channel_id', 'H2H'),
        );

        $responseVa = data_get($response, 'virtualAccountData.virtualAccountNo')
            ?? data_get($response, 'virtualAccountData.virtualAccountNumber');
        $responseCustomerNo = data_get($response, 'virtualAccountData.customerNo')
            ?? $payload['customerNo'];

        if (! filled($responseVa)) {
            throw new DokuException('DOKU tidak mengembalikan nomor Virtual Account.', $response);
        }

        return [
            'gateway' => 'doku',
            'bank' => $channel->code,
            'channel' => $channel->channel,
            'doku_va_channel_id' => $channel->id,
            'partner_service_id' => trim($partnerServiceId),
            'provider_account_id' => $trxId,
            'provider_customer_id' => $responseCustomerNo,
            'account_number' => (string) $responseVa,
            'status' => 'active',
            'metadata' => $response,
        ];
    }

    public function verifyWebhook(array $headers, string $rawBody, string $path): bool
    {
        $timestamp = $headers['x-timestamp'] ?? $headers['X-TIMESTAMP'] ?? null;
        $signature = $headers['x-signature'] ?? $headers['X-SIGNATURE'] ?? null;
        $partnerId = $headers['x-partner-id'] ?? $headers['X-PARTNER-ID'] ?? null;
        if (! filled($timestamp) || ! filled($signature)) {
            return false;
        }
        if (filled($partnerId) && filled(config('doku.client_id')) && ! hash_equals((string) config('doku.client_id'), (string) $partnerId)) {
            return false;
        }

        try {
            $accessToken = $this->client->accessToken();
        } catch (DokuException) {
            return false;
        }

        $expected = DokuSigner::snapRequestSignature(
            'POST',
            '/' . ltrim($path, '/'),
            $accessToken,
            $rawBody,
            $timestamp,
            (string) config('doku.secret_key'),
        );
        return hash_equals($expected, $signature);
    }

    private function createInvoiceVa(BillingInvoice $invoice): array
    {
        $account = $invoice->member->paymentAccounts()->where('gateway', 'doku')->where('status', 'active')->orderByDesc('is_default')->first();
        if (! $account) {
            throw new DokuException('Member belum memiliki Virtual Account DOKU aktif. Buat Virtual Account dari detail member terlebih dahulu.');
        }

        $trxId = 'INV-' . $invoice->id . '-' . Str::lower(Str::random(8));
        $partnerServiceId = $account->partner_service_id ?: data_get($account->metadata, 'partner_service_id');
        if (! filled($partnerServiceId)) {
            throw new DokuException('Partner Service ID pada Virtual Account member belum tersedia.');
        }

        $payload = [
            'partnerServiceId' => $this->normalizePartnerServiceId((string) $partnerServiceId),
            'customerNo' => $account->provider_customer_id,
            'virtualAccountNo' => $account->account_number,
            'virtualAccountName' => Str::limit($invoice->member->username, 255, ''),
            'trxId' => $trxId,
            'totalAmount' => [
                'value' => number_format((int) $invoice->amount, 2, '.', ''),
                'currency' => 'IDR',
            ],
            'additionalInfo' => [
                'channel' => $account->channel,
                'virtualAccountConfig' => [
                    'reusableStatus' => true,
                ],
            ],
            'virtualAccountTrxType' => 'C',
        ];

        $response = $this->client->postSnap(
            '/virtual-accounts/bi-snap-va/v1.1/transfer-va/update-va',
            $payload,
            config('doku.channel_id', 'H2H'),
        );

        return [
            'gateway' => 'doku',
            'channel' => 'va_' . strtolower($account->bank),
            'provider_reference' => $trxId,
            'payment_url' => null,
            'qr_content' => null,
            'expires_at' => null,
            'metadata' => $response,
        ];
    }

    private function createQris(BillingInvoice $invoice): array
    {
        $merchantId = config('doku.merchant_id');
        $terminalId = config('doku.terminal_id');
        if (! filled($merchantId) || ! filled($terminalId)) {
            throw new DokuException('DOKU QRIS membutuhkan DOKU_MERCHANT_ID dan DOKU_TERMINAL_ID.');
        }

        $expires = now()->addMinutes(30)->format('Y-m-d\TH:i:sP');
        $payload = [
            'partnerReferenceNo' => 'INV-' . $invoice->id . '-' . Str::upper(Str::random(8)),
            'amount' => [
                'value' => number_format((int) $invoice->amount, 2, '.', ''),
                'currency' => 'IDR',
            ],
            'merchantId' => (string) $merchantId,
            'terminalId' => (string) $terminalId,
            'validityPeriod' => $expires,
            'additionalInfo' => [
                'feeType' => '1',
            ],
        ];

        $response = $this->client->postSnap('/snap-adapter/b2b/v1.0/qr/qr-mpm-generate', $payload, 'H2H');
        $qr = data_get($response, 'qrContent');
        if (! filled($qr)) {
            throw new DokuException('DOKU tidak mengembalikan QR content.', $response);
        }

        return [
            'gateway' => 'doku',
            'channel' => 'qris',
            'provider_reference' => $payload['partnerReferenceNo'],
            'payment_url' => null,
            'qr_content' => $qr,
            'expires_at' => $expires,
            'metadata' => $response,
        ];
    }

    private function customerNumber(int $memberId, string $prefix = ''): string
    {
        $memberPart = (string) $memberId;
        $available = 20 - strlen($prefix);
        if ($available < 1 || strlen($memberPart) > $available) {
            throw new DokuException('ID member terlalu panjang untuk format customerNo DOKU.');
        }

        return $prefix . str_pad($memberPart, $available, '0', STR_PAD_LEFT);
    }

    private function normalizeCustomerPrefix(?string $value): string
    {
        $value = trim((string) $value);
        if ($value === '') {
            return '';
        }
        if (! preg_match('/^\d{1,20}$/', $value)) {
            throw new DokuException('Prefix Customer No DOKU harus berupa angka.');
        }

        return $value;
    }

    private function normalizePartnerServiceId(string $value): string
    {
        $value = preg_replace('/\D+/', '', trim($value));
        if ($value === '' || strlen($value) > 8) {
            throw new DokuException('Kode merchant DOKU (Partner Service ID) harus 1-8 digit.');
        }

        return str_pad($value, 8, ' ', STR_PAD_LEFT);
    }

    private function buildVirtualAccountNumber(string $partnerServiceId, string $customerNo): string
    {
        return $partnerServiceId . $customerNo;
    }
}
