<?php

return [
    'enabled' => (bool) env('DOKU_ENABLED', false),
    'environment' => env('DOKU_ENVIRONMENT', 'sandbox'),
    'base_url' => env('DOKU_BASE_URL', 'https://api-sandbox.doku.com'),
    'client_id' => env('DOKU_CLIENT_ID'),
    'secret_key' => env('DOKU_SECRET_KEY'),
    'api_key' => env('DOKU_API_KEY'),
    'doku_public_key' => null,
    'private_key_path' => env('DOKU_PRIVATE_KEY_PATH'),
    'private_key_passphrase' => env('DOKU_PRIVATE_KEY_PASSPHRASE'),
    'public_key_path' => env('DOKU_PUBLIC_KEY_PATH', '/etc/xd-radius/doku/public.key'),
    'key_fingerprint' => null,
    'merchant_id' => env('DOKU_MERCHANT_ID'),
    'terminal_id' => env('DOKU_TERMINAL_ID'),
    'channel_id' => env('DOKU_CHANNEL_ID', 'H2H'),
    'va_bank' => env('DOKU_VA_BANK', 'BNI'),
    'va_partner_service_id' => env('DOKU_VA_PARTNER_SERVICE_ID'),
    'va_customer_prefix' => env('DOKU_VA_CUSTOMER_PREFIX', '3'),
    'notification_path' => env('DOKU_NOTIFICATION_PATH', '/webhooks/doku'),
    'timeout' => (int) env('DOKU_HTTP_TIMEOUT', 15),
    'va_banks' => [
        'BCA' => ['name' => 'BCA', 'channel' => 'VIRTUAL_ACCOUNT_BCA'],
        'BNI' => ['name' => 'BNI', 'channel' => 'VIRTUAL_ACCOUNT_BNI'],
        'BRI' => ['name' => 'BRI', 'channel' => 'VIRTUAL_ACCOUNT_BRI'],
        'BSI' => ['name' => 'BSI', 'channel' => 'VIRTUAL_ACCOUNT_BSI'],
        'BNC' => ['name' => 'BNC', 'channel' => 'VIRTUAL_ACCOUNT_BNC'],
        'BTN' => ['name' => 'BTN', 'channel' => 'VIRTUAL_ACCOUNT_BTN'],
        'BSS' => ['name' => 'BSS', 'channel' => 'VIRTUAL_ACCOUNT_BSS'],
        'MANDIRI' => ['name' => 'Bank Mandiri', 'channel' => 'VIRTUAL_ACCOUNT_BANK_MANDIRI'],
        'CIMB' => ['name' => 'CIMB Niaga', 'channel' => 'VIRTUAL_ACCOUNT_BANK_CIMB'],
        'PERMATA' => ['name' => 'Permata', 'channel' => 'VIRTUAL_ACCOUNT_BANK_PERMATA'],
        'DANAMON' => ['name' => 'Danamon', 'channel' => 'VIRTUAL_ACCOUNT_BANK_DANAMON'],
    ],
];
